version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017

  gorse:
    image: zhenghaoz/gorse-in-one
    restart: unless-stopped
    ports:
      - 8086:8086 # gRPC port
      - 8088:8088 # HTTP port
    environment:
      # Use Redis as cache storage backend.
      GORSE_CACHE_STORE: redis://redis:6379
      # Use MongoDB as data storage backend.
      GORSE_DATA_STORE: mongodb://mongo:27017/data
    command: >
      -c /etc/gorse/config.toml  --log-path /var/log/gorse/master.log  --cache-path /var/lib/gorse/master_cache.data
    volumes:
      # Mount the configuration file.
      - ./config.toml:/etc/gorse/config.toml
    depends_on:
      - redis
      - mongo

  data-refresh:
    build:
      context: ./data-refresh
      dockerfile: Dockerfile
    env_file:
      - data-refresh/.env
    depends_on:
      - mongo
      - gorse

  server:
    depends_on:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - backend/.env
